# Generated by Django 2.0.5 on 2019-10-03 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='graph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_nodo_name', models.CharField(max_length=45)),
                ('target_nodo_name', models.CharField(max_length=45)),
                ('weight_edge', models.FloatField(blank=True, default=None)),
            ],
        ),
    ]
