# Generated by Django 2.0.5 on 2019-10-03 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0003_auto_20191003_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graph',
            name='weight_edge',
            field=models.IntegerField(),
        ),
    ]
