# Generated by Django 2.0.5 on 2019-10-03 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0004_auto_20191003_1825'),
    ]

    operations = [
        migrations.CreateModel(
            name='source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_node', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_node', models.CharField(max_length=45)),
                ('weight_edge', models.IntegerField()),
                ('source_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routes.source')),
            ],
        ),
        migrations.DeleteModel(
            name='graph',
        ),
    ]
