# Generated by Django 2.0.5 on 2019-10-03 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0005_auto_20191003_1849'),
    ]

    operations = [
        migrations.CreateModel(
            name='graph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_node', models.CharField(max_length=45)),
                ('target_node', models.CharField(max_length=45)),
                ('weight_edge', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_node', models.CharField(max_length=45)),
                ('target_node', models.CharField(max_length=45)),
            ],
        ),
        migrations.RemoveField(
            model_name='target',
            name='source_node',
        ),
        migrations.DeleteModel(
            name='source',
        ),
        migrations.DeleteModel(
            name='target',
        ),
    ]
